version: '3.8'

services:

  # Apache con PHP
  pagina_web:
    build: .
    container_name: apache
    ports:
      - "81:80"
    volumes:
      - ./html:/var/www/html

  # MySQL
  mysql:
    image: mysql:latest
    container_name: mysql_lamp
    environment:
      MYSQL_ROOT_PASSWORD: Alumne_8
      MYSQL_DATABASE: lamp_db
      MYSQL_USER: usuario1
      MYSQL_PASSWORD: Alumne_9
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_lamp
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: Alumne_8
    ports:
      - "82:80"

  # Adminer
  adminer:
    image: adminer_lamp
    container_name: adminer
    ports:
      - "83:8080"
